service: hemnet-webscraper-notifier

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws # https://serverless.com/framework/docs/providers/aws/
  endpointType: REGIONAL
  runtime: nodejs10.x
  memorySize: 256 # optional, in MB, default is 1024
  timeout: 30 # optional, in seconds, default is 6
  logRetentionInDays: 14 # Set the default RetentionInDays for a CloudWatch LogGroup
  region: ${self:custom.defaultRegion}
  stage: ${env:NODE_ENV, self:custom.defaultNodeEnv}
  environment: # Service wide environment variables, which are added from dotenv plugin
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_SEARCH_RESULT}"
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: "*"
  apiGateway:
    description: API Gateway or serving node app scraping Hemnet data and sending notifications # Not Added, probably bug

functions:
  http:
    handler: src/index.api
    name: ${self:provider.stage}-${self:service}
    timeout: 30
    description: Serving node app scraping Hemnet data
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
  webscrape:
    handler: src/index.cron
    name: ${self:provider.stage}-${self:service}-cron
    description: Crone - node app scraping Hemnet data and sending notifications # optional, Description to publish to AWS
    events:
      # Invoke Lambda function every 10 minutes
      - schedule: rate(10 minutes)

resources:
  Resources:
    webscraperDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain # Keeps around the DynamoDB resource when we redeploy/destroy
      Properties:
        TableName: ${self:provider.environment.TABLE_SEARCH_RESULT}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: pubDate # **2015-12-21T17:42:34Z** 2016-02-15 20150311T122706Z
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: pubDate
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  defaultRegion: eu-central-1
  defaultNodeEnv: dev
  dotenv:
    include:
      - TABLE_SEARCH_RESULT
      - RSS_HEMNET_URL
      - SOURCE_EMAIL
      - TO_EMAILS
      - DIRECTION_MATRIX_API_ENDPOINT
      - GOOGLE_API_KEY
      - CITY
      - COUNTRY_CODE
      - FROM_ADDRESS
